### ISSUE TITLE
Get-SonarrSeries : Failed to parse JSON response into the specified object

### ISSUE THREAD

**Issue by tsgadam** [Yevrag35/PoshSonarr#56]
Hi,

I had this working fine for a while, however at some point it began failing with the below error:

Get-SonarrSeries : Failed to parse JSON response into the specified object.  The response content was malformed, blank, or null.

Long story short, I'm trying to use PoshSonarr to query all series with a specific tag (as shown below) however it fails when running Get-SonarrSeries whether this includes the WHERE statement or not.

So just running a basic Get-SonarrSeries fails with the same error.

My suspicion is that one of the series has characters that are not being parsed causing it to fail, however I don't know how to start digging into that other than manually skimming through the list of 1700+ shows.

Could this also be caused by too many records being returned?

Any way, hope you can help, and my full script is below for reference.

Thanks in advance

Script

Import-Module PoshSonarr
Connect-Sonarr -SonarrUrl "http://SERVERNAME:8989" -ApiKey "APIKEYHERE"
$BackupTagID = Get-SonarrTag | where {$_.Label -eq 'backup'} | Select ID
$BackupTagID = $BackupTagID.Id
$ShowsToBackup = Get-SonarrSeries | where {$_.Tags -contains $BackupTagID}| Sort-Object Name | select Name, path, tags 
$BackupFile = ForEach ($Show in $ShowsToBackup){
$ShowPath = $Show.Path 
$ShowSourcePath = $ShowPath.Replace('\\SERVERNAME\O', 'O:')
$ShowBackupPath = $ShowPath.Replace('\\SERVERNAME\O', 'B:\Backups\SERVERNAME\O')
$BackupCommand = 'robocopy "'+$ShowSourcePath+'" "'+$ShowBackupPath+'" /mir /r:1 /XJF /XJD'
write-output $BackupCommand
}
$BackupFile | Out-File -FilePath "\\SERVERNAME\B\Backups\SERVERNAME\C\Program Files\Scheduled Tasks\SonarrBackupContent.bat" -Encoding ascii

**Comment by Yevrag35** [comment]
Hey there, so it could be due to an update changing certain things in the output object which has happened before.

To help me find where in the JSON deserialization it's failing, can you do the following and tell me what you see in the output:

```powershell
$ErrorActionPreference = "Stop"
Get-SonarrSeries  # I'm expecting this to produce the error
$ex = $error[0].Exception.GetBaseException()
$ex | select *
```

If you could copy the output from the `$ex | Select *`, that should hopefully help tell us where in the process it's failing.

Thanks!

**Comment by Yevrag35** [comment]
I actually found the issue, and am now creating a hotfix

**Comment by Yevrag35** [comment]
v1.4.6 has been published to the PowerShell Gallery.  When it indexes there go ahead and update your version.  It should take care of the issue - but if not feel free to reopen this.

Thanks for the details in your issue.

**Comment by tsgadam** [comment]
Hi Mike,

Thank you for such a rapid response, sadly however this has not resolved the issue.

I can confirm that I've pulled the latest version:
PS C:\Windows\system32> Get-Module -Name PoshSonarr

ModuleType Version    Name                                ExportedCommands                        
---------- -------    ----                                ----------------                        
Script     1.4.6      PoshSonarr                          {Add-Release, Add-Series, Add-Tag, Cl...


I've also ran the error trap you originally requested and this does not appear to give any additional output:
PS C:\Windows\system32> Get-SonarrSeries  # I'm expecting this to produce the error

Get-SonarrSeries : Failed to parse JSON response into the specified object.  The response content 
was malformed, blank, or null.
At line:1 char:1
+ Get-SonarrSeries  # I'm expecting this to produce the error
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-SonarrSeries], ParseJsonResponseExceptio 
   n
    + FullyQualifiedErrorId : MG.Api.Json.ParseJsonResponseException,MG.Sonarr.Cmdlets.GetSeries


PS C:\Windows\system32> $ex = $error[0].Exception.GetBaseException()

You cannot call a method on a null-valued expression.
At line:1 char:1
+ $ex = $error[0].Exception.GetBaseException()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
PS C:\Windows\system32> $ex | select *




Please let me know if you want me to try anything else to troubleshoot this :)

Cheers

Adam

**Comment by Yevrag35** [comment]
Bummer... okay let's try just this:

```powershell
$ErrorActionPreference = "Stop"
Get-SonarrSeries  # I'm expecting this to produce the error
$error[0].Exception | Select *
```

Just incentivizes me further to finally remake this module.

**Comment by tsgadam** [comment]
I've given that a go and there is still no output from the $error[0].Exception | Select * line

:(

It's a great module even though I use just a fraction of it's function, and it'd be great to be able to do the same on Radarr too! ;)

**Comment by Yevrag35** [comment]
Is there "anything" in `$error` at all?

**Comment by tsgadam** [comment]
Doesn't look like it.  I've just cleared $error and reran fresh and only get this:

PS C:\Windows\system32> $error
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to parse JSON response into the specified object.  The response content was 
malformed, blank, or null.
Get-SonarrSeries : Failed to parse JSON response into the specified object.  The response content was malformed, blank, or null.
At line:1 char:1
+ Get-SonarrSeries  # I'm expecting this to produce the error
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-SonarrSeries], ParseJsonResponseException
    + FullyQualifiedErrorId : MG.Api.Json.ParseJsonResponseException,MG.Sonarr.Cmdlets.GetSeries

**Comment by Yevrag35** [comment]
Ok, you should be able to see something with this then:
`$error[0] | Select *`

**Comment by tsgadam** [comment]
That's spat out some more info:

PS C:\Windows\system32> $error[0] | Select *


ErrorRecord                 : Failed to parse JSON response into the specified object.  The response content was malformed, blank, or null.
WasThrownFromThrowStatement : False
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to parse JSON response into the specified 
                              object.  The response content was malformed, blank, or null.
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : 
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                              --- End of stack trace from previous location where exception was thrown ---
                                 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087



I'm not on Discord though :(

**Comment by Yevrag35** [comment]
Ok, well - I published a new-new version (1.4.7) that gets rid of most of the Enum's.  I'm hoping that at least 1 of them is causing the issue.  See if that works.

**Comment by tsgadam** [comment]
I was already on the 1.4.7 version after you'd published it, and I've just removed and installed it again to be sure, so these errors relate to that.

**Comment by Yevrag35** [comment]
Great... must be something else then.  I do see the ErrorRecord has stuff, so let's try:
```powershell
$ex = $error[0]
$ex.ErrorRecord | Select *
$ex.ErrorRecord.Exception | Select *
```

**Comment by tsgadam** [comment]
Here you go :)


PS C:\Windows\system32> $ex = $error[0]
$ex.ErrorRecord | Select *
$ex.ErrorRecord.Exception | Select *



writeErrorStream      : True
PSMessageDetails      : 
Exception             : MG.Api.Json.ParseJsonResponseException: Failed to parse JSON response into the specified object.  The response content was malformed, blank, or null. ---> 
                        Newtonsoft.Json.JsonSerializationException: Error converting value "deleted" to type 'MG.Sonarr.Functionality.SeriesStatusType'. Path '[1534].status', line 202756, position 23. 
                        ---> System.ArgumentException: Requested value 'deleted' was not found.
                           at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
                           at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                           --- End of inner exception stack trace ---
                           at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, 
                        JsonProperty containerProperty, JsonReader reader, Object target)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                        containerContract, JsonProperty containerMember, Object existingValue)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, 
                        JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, 
                        String id)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, 
                        JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                           at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                           at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                           at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                           at MG.Api.Json.Extensions.HttpContentExtensions.<ReadAsJsonAsync>d__1`1.MoveNext()
                           --- End of inner exception stack trace ---
                           at MG.Api.Json.Extensions.HttpContentExtensions.<ReadAsJsonAsync>d__1`1.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at MG.Api.Json.Extensions.HttpClientExtensions.<GenerateMultipleResponse>d__5`1.MoveNext()
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [Get-SonarrSeries], ParseJsonResponseException
FullyQualifiedErrorId : MG.Api.Json.ParseJsonResponseException,MG.Sonarr.Cmdlets.GetSeries
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {0, 1}
Message        : Failed to parse JSON response into the specified object.  The response content was malformed, blank, or null.
Data           : {}
InnerException : Newtonsoft.Json.JsonSerializationException: Error converting value "deleted" to type 'MG.Sonarr.Functionality.SeriesStatusType'. Path '[1534].status', line 202756, position 23. ---> 
                 System.ArgumentException: Requested value 'deleted' was not found.
                    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    --- End of inner exception stack trace ---
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, 
                 JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                    at MG.Api.Json.Extensions.HttpContentExtensions.<ReadAsJsonAsync>d__1`1.MoveNext()
TargetSite     : Void MoveNext()
StackTrace     :    at MG.Api.Json.Extensions.HttpContentExtensions.<ReadAsJsonAsync>d__1`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at MG.Api.Json.Extensions.HttpClientExtensions.<GenerateMultipleResponse>d__5`1.MoveNext()
HelpLink       : 
Source         : MG.Api.Json
HResult        : -2146233088

**Comment by Yevrag35** [comment]
Ok, can you absolutely be sure that your version is at 1.4.7, because the Enum value it's complaining about I got rid of in that version.
`Error converting value "deleted" to type 'MG.Sonarr.Functionality.SeriesStatusType'.`

**Comment by tsgadam** [comment]
Definitely 1.4.7 I'm afraid



PS C:\Windows\system32> get-module -Name PoshSonarr

ModuleType Version    Name                                ExportedCommands                                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                                   
Script     1.4.7      PoshSonarr                          {Add-Release, Add-Series, Add-Tag, Clear-Log...}

**Comment by Yevrag35** [comment]
Are you PowerShell Core or PowerShell 5.1?

**Comment by Yevrag35** [comment]
Also, I can 100% confirm that the published 1.4.7 version, absolutely, should have no reference of a type called `SeriesStatusType` anymore.

**Version 1.4.6**
![image](https://github.com/Yevrag35/PoshSonarr/assets/20248838/9df68da8-7b60-4225-a899-8e570763d0d6)

**Version 1.4.7**
![image](https://github.com/Yevrag35/PoshSonarr/assets/20248838/04283bde-8e5a-4ef2-9ba9-4dacb24c24a1)

**Comment by tsgadam** [comment]
I'm running PowerShell 5.1.xxx



PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                                                                         
----                           -----                                                                                                                                                                         
PSVersion                      5.1.22621.1778                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                       
BuildVersion                   10.0.22621.1778                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                           
SerializationVersion           1.1.0.1

**Comment by tsgadam** [comment]
How can I check the functionality options like you've shown?

I'm only using PowerShell ISE

**Comment by Yevrag35** [comment]
Ah, you're using ISE.  ISE does not do a good job of overwriting previously loaded modules - so my suggestion would be to do the following:

Your modules are normally installed to 1 of 2 places:
CurrentUser: %USERPROFILE%\Documents\WindowsPowerShell\Modules
LocalMachine: %PROGRAMFILES%\WindowsPowerShell\Modules

1. Close ISE
1. Find the PoshSonarr folder in either directory and completely delete it.  Then run this in a normal (non-ISE) PowerShell window as an administrator:
```powershell
Install-Module PoshSonarr -RequiredVersion 1.4.7
```
1. Close the PowerShell window
1. Relaunch ISE and test your script.

**Comment by tsgadam** [comment]
That's cracked it! :)

So the amendment you made was fine, I just got stuck within ISE which obviously wasn't getting the latest module version loaded as you said.

Thank you for sorting that out, it's been bugging me for a while but I should have raised this sooner :)

**Comment by tsgadam** [comment]
Tested working and closed issue.

**Comment by Yevrag35** [comment]
Ok, good lol.  I was starting to go crazy XD

Glad it works now.  I will say though, you should move to PowerShell 7 if you can.  When I rework this module, it's going to only work for PowerShell 7.

**Comment by tsgadam** [comment]
I’ll get myself upgraded to PS7 as I don’t want to lose access to your module :)

Hope you develop one for Radar too, that’d be ace!
Thanks again!
